apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  annotations:
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.18.17
    cdi.kubevirt.io/dataImportCron: rhel9-image-cron
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: rhel.9
    kubevirt.io/dynamic-credentials-support: "true"
  name: rhel9
  namespace: openshift-virtualization-os-images
spec:
  source:
    snapshot:
      name: rhel9-2f2cf92fff21
      namespace: openshift-virtualization-os-images
