apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    cdi.kubevirt.io/storage.import.imageStreamDockerRef: registry.redhat.io/rhel8/rhel-guest-image@sha256:684cedbd2c18d0601f7bf97a424ea199b5ce69559687584923e473edc753dc70
    cdi.kubevirt.io/storage.import.lastCronTime: "2025-10-17T04:51:00Z"
    cdi.kubevirt.io/storage.import.nextCronTime: "2025-10-17T16:51:00Z"
    cdi.kubevirt.io/storage.import.sourceDesiredDigest: sha256:684cedbd2c18d0601f7bf97a424ea199b5ce69559687584923e473edc753dc70
    cdi.kubevirt.io/storage.import.storageClass: ocs-storagecluster-ceph-rbd-virtualization
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
  labels:
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    app.kubernetes.io/name: data-sources
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.18.17
  name: rhel8-image-cron
  namespace: openshift-virtualization-os-images
spec:
  garbageCollect: Outdated
  managedDataSource: rhel8
  schedule: 51 4/12 * * *
  template:
    metadata: {}
    spec:
      source:
        registry:
          imageStream: rhel8-guest
          pullMethod: node
      storage:
        resources:
          requests:
            storage: 30Gi
    status: {}
