apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.18.8
    cdi.kubevirt.io/dataImportCron: rhel10-beta-image-cron
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: rhel.10
    kubevirt.io/dynamic-credentials-support: "true"
  name: rhel10-beta
  namespace: openshift-virtualization-os-images
spec:
  source:
    snapshot:
      name: rhel10-beta-8a0eb850f419
      namespace: openshift-virtualization-os-images
