apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineset-admin
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  - machinesets/scale
  verbs:
  - patch
  - update
  resourceNames: 
  - <exact-name-of-machineset>
  - <exact-name-of-machineset>
  - <exact-name-of-machineset>
  - <exact-name-of-machineset>
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - get
  - list

