apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: platform-standard-service
  tags:
    - platform-managed
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
