---
- name: credentials | Set credentials variable
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: "{{ aap_seed_controller_credentials | default([]) }}"
  no_log: "{{ aap_seed_secure_logging }}"

- name: credentials | Build AAP Credential
  when:
    - aap_seed_aap_credentials_create | default(true)
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials + [lookup('template', 'aap_credential.yml.j2')
      | ansible.builtin.from_yaml] }}
  no_log: "{{ aap_seed_secure_logging }}"

- name: credentials | Build Automation Hub Credentials
  when:
    - aap_seed_automation_hub_credentials_create | default(true)
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials + (aap_seed_automation_hub_credentials | default([])) }}
  no_log: "{{ aap_seed_secure_logging }}"

- name: credentials | Build Project Credential
  when:
    - aap_seed_project_credentials_create | default(true)
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials + [lookup('template', 'git_credential.yml.j2')
      | ansible.builtin.from_yaml] }}
  no_log: "{{ aap_seed_secure_logging }}"

- name: credentials | Build Container Registry Credential
  when:
    - aap_seed_container_registry_credentials_create | default(true)
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials + [lookup('template', 'container_registry_credential.yml.j2')
      | ansible.builtin.from_yaml] }}
  no_log: "{{ aap_seed_secure_logging }}"

- name: credentials | Build Operator Management Credentials
  when:
    - aap_seed_migration_targets_credentials_create | default(true)
  block:
    - name: credentials | Build Migration Target Credentials
      when:
        - groups['migration_spoke'] | length > 0
        - hostvars[groups['migration_spoke'][0]]['migration_targets'] | default([]) | length > 0
      ansible.builtin.set_fact:
        aap_seed_controller_credentials: >-
          {{ aap_seed_controller_credentials +
          [lookup('template', migration_target['type'] ~ '/target_credential.yml.j2')
          | ansible.builtin.from_yaml] }}
      loop: "{{ hostvars[groups['migration_spoke'][0]]['migration_targets'] }}"
      loop_control:
        loop_var: "migration_target"
      vars:
        _target_name: "{{ migration_target['name'] | infra.openshift_virtualization_migration.rfc1123 }}"
      no_log: "{{ aap_seed_secure_logging }}"

    - name: credentials | Build required credentials
      ansible.builtin.include_tasks: _build_credentials.yml
      loop: "{{ (groups['migration_hub'] + groups['migration_spoke']) | ansible.builtin.unique }}"
      loop_control:
        loop_var: _mf_host
...
