---
- name: Set controller_configuration vars
  ansible.builtin.set_fact:
    aap_seed_controller_dependency_check: "{{ aap_seed_controller_dependency_check }}"
    aap_seed_controller_configuration_async_retries: "{{ aap_seed_controller_configuration_async_retries }}"
    "{{ aap_seed_controller_organizations_var }}": "{{ aap_seed_controller_organizations if (aap_seed_organization_create | default(true) | bool) else [] }}"  # noqa: var-naming[no-jinja]  # noqa: yaml[line-length]
    aap_seed_controller_projects: >-
      {{ aap_seed_controller_projects if (aap_seed_projects_create | default(true) | bool) else [] }}
    aap_seed_controller_execution_environments: >-
      {{ aap_seed_controller_execution_environments if (aap_seed_execution_environments_create | default(true)
      | bool) else [] }}
    aap_seed_controller_credential_types: >-
      {{ aap_seed_controller_credential_types if (aap_seed_credential_types_create | default(true)
      | bool) else [] }}
    aap_seed_controller_inventories: >-
      {{ aap_seed_controller_inventories if (aap_seed_inventories_create | default(true)
      | bool) else [] }}
    aap_seed_controller_hosts: >-
      "{{ aap_seed_controller_hosts if (aap_seed_hosts_create | default(true) | bool) else [] }}"

- name: Build Credentials
  ansible.builtin.include_tasks:
    file: credentials.yml

- name: Build Job Templates
  ansible.builtin.include_tasks:
    file: job_templates.yml
  when: aap_seed_job_templates_create | default(true) | bool

- name: Build Workflows
  ansible.builtin.include_tasks:
    file: workflows.yml
  when: aap_seed_workflow_job_templates_create | default(true) | bool

- name: Ensure AAP API credentials are set
  ansible.builtin.assert:
    that:
      - aap_seed_controller_hostname | default("", true) | trim | length > 0
      - aap_seed_controller_username | default("", true) | trim | length > 0 and
        aap_seed_controller_password | default("", true) | trim | length > 0 or
        aap_seed_controller_token | default("", true) | trim | length > 0
    fail_msg: "AAP API credentials are not set correctly. Please check your configuration."

- name: Check if both username/password and token are defined
  when:
    - aap_seed_controller_username | default("", true) | trim | length > 0
    - aap_seed_controller_password | default("", true) | trim | length > 0
    - aap_seed_controller_token | default("", true) | trim | length > 0
  ansible.builtin.debug:
    msg: "Both username/password and token are defined. Using token for API calls."

- name: Wait for API to become available using username and password
  when:
    - aap_seed_controller_token | default("", true) | length > 0
  retries: 300
  delay: 5
  register: aap_seed_api_status
  until: aap_seed_api_status.status == 200
  ansible.builtin.uri:
    url: https://{{ aap_seed_controller_hostname }}/api{{ '/controller' if aap_version is not defined or aap_version is defined and aap_version is version('2.5', '>=') }}/v2/config/ # noqa: yaml[line-length]
    method: GET
    user: "{{ aap_seed_controller_username }}"
    password: "{{ aap_seed_controller_password }}"
    body_format: json
    validate_certs: false
    force_basic_auth: true

- name: Wait for API to become available using token
  when:
    - aap_seed_controller_token | default("", true) | length > 0
  retries: 300
  delay: 5
  register: aap_seed_api_status
  until: aap_seed_api_status.status == 200
  ansible.builtin.uri:
    url: https://{{ aap_seed_controller_hostname }}/api{{ '/controller' if aap_version is not defined or aap_version is defined and aap_version is version('2.5', '>=') }}/v2/config/ # noqa: yaml[line-length]
    method: GET
    headers:
      Authorization: "Bearer {{ aap_seed_controller_token }}"
    body_format: json
    validate_certs: false

- name: Call dispatch role
  ansible.builtin.include_role:
    name: "{{ aap_seed_cac_collection }}.dispatch"
  vars:
    controller_configuration_secure_logging: false # noqa: var-naming[no-role-prefix]
...
