[req]
prompt = no
req_extensions = req_ext
distinguished_name = dn
 
[ dn ]
C=US
ST=North Carolina
L=Raleigh
O=Red Hat 
OU=Information Technology
emailAddress=myemail@corporate.com
CN = *.apps.<cluster-name>.<base-domain>
 
[ req_ext ]
subjectAltName = @alt_names
#keyUsage = digitalSignature, keyEncipherment
#extendedKeyUsage = serverAuth
 
[ alt_names ]
DNS.1 = *.apps.<cluster-name>.<base-domain>
DNS.2 = api.<cluster-name>.<base-domain>
