apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: cpumanager-enabled
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: cpumanager-enabled
  kubeletConfig:
     cpuManagerPolicy: static # none or static. none is the default and does nothing.
     cpuManagerReconcilePeriod: 5s # reconcile frequency. Default is 5 seconds
