---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim
  labels:
    app: httpd-frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
spec:
#  securityContext:
#    seccompProfile: 
#      type: RuntimeDefault 
#    runAsNonRoot: true 
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/httpd-24
        imagePullPolicy: Always
        name: httpd-rhel8
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8080
          #hostPort: 8080
          name: http-port
        - containerPort: 8443
          #hostPort: 8443
          name: https-port
        volumeMounts:
        - name: httpd-persistent-storage
          mountPath: /home/httpd-server
      volumes:
      - name: httpd-persistent-storage
        persistentVolumeClaim:
          claimName: httpd-pv-claim
---
