apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
#  featureGates:
#    - MCPServer
#  mcpServers:   # Old Format, 1.0.9
#    - name: my-mcp-server
#      streamableHTTP:
#        url: 'http://my-mcp-server.example.svc.cluster.local:8085/mcp'
#        timeout: 5
#        enableSSE: false
#        sseReadTimeout: 10
#  mcpServers:   # New Format 1.0.10
#    - name: rhokp-mcp
#      url: 'http://rhokp-mcp.rhokp-server.svc.cluster.local:8000/mcp'
#      timeout: 30
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: gpt-oss:120b
        name: my-ollama
        type: openai
        url: 'http://ollama.ollama.svc.cluster.local:11434/v1'  # Not sure that this is correct
  ols:
    #rag:
    #  - image: quay.io/<username>/my-byok-image:latest
    #byokRAGOnly: true  # Set true to disable knowledge inside the operator and only use RHOKP
    #storage:
    #  size: 768Mi
    #  class: gp3-csi
    #introspectionEnabled: true  # give OpenShift Lightspeed cluster-specific context.
    conversationCache:
      postgres:
        credentialsSecret: lightspeed-redis-secret
        dbName: postgres
        maxConnections: 2000
        sharedBuffers: 256MB
        user: postgres
        #maxMemory: 1024mb
        #maxMemoryPolicy: allkeys-lru
      type: postgres
    defaultModel: gpt-oss:120b
    defaultProvider: my-ollama
    deployment:
      console:
        replicas: 1
      replicas: 1
    logLevel: INFO
    #quotaHandlersConfig:
    #  limitersConfig:
    #  - name: user_limits
    #    type: user_limiter
    #    initialQuota: 100000
    #    quotaIncrease: 1000
    #    period: 30 days
    #  - name: cluster_limits
    #    type: cluster_limiter
    #    initialQuota: 1000000
    #    quotaIncrease: 100000
    #    period: 30 days
  olsDataCollector:
    logLevel: INFO
