apiVersion: v1
kind: Pod
metadata:
  name: host-debug-pod
  labels:
    app: debug
spec:
  nodeName: "worker-1"
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: numa-toolbox-container
    image: registry.access.redhat.com/ubi9/ubi
    command: ["/bin/bash", "-c", "sleep infinity"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: host-sys
      mountPath: /sys
    - name: host-proc
      mountPath: /proc
    - name: host-dev
      mountPath: /dev
  volumes:
  - name: host-sys
    hostPath:
      path: /sys
  - name: host-proc
    hostPath:
      path: /proc
  - name: host-dev
    hostPath:
      path: /dev
  restartPolicy: Never
